name: background_location_sender
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^12.0.3
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.1
  google_maps_flutter: ^2.2.1
  intl: ^0.17.0
  location: ^4.4.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  workmanager: ^0.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
