// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsR93s-8MNaoUEOsf7AEg14sf_d1vO920',
    appId: '1:218641175293:web:e58bd054db8e3e863ee494',
    messagingSenderId: '218641175293',
    projectId: 'backgroundlocation-570a9',
    authDomain: 'backgroundlocation-570a9.firebaseapp.com',
    storageBucket: 'backgroundlocation-570a9.appspot.com',
    measurementId: 'G-57DGFLRS8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7MKVjhgsuKzrMAGcfrdvzLY9YvkGt5OY',
    appId: '1:218641175293:android:16bcaf64aa3b7c2d3ee494',
    messagingSenderId: '218641175293',
    projectId: 'backgroundlocation-570a9',
    storageBucket: 'backgroundlocation-570a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpQhbHGQgKRUXLLJOfsJV30kLRYCplkc0',
    appId: '1:218641175293:ios:b4d8d7f9a046afdf3ee494',
    messagingSenderId: '218641175293',
    projectId: 'backgroundlocation-570a9',
    storageBucket: 'backgroundlocation-570a9.appspot.com',
    iosClientId: '218641175293-2hlcthlvd7afklji46qjeqpuc6moqbsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.backgroundLocationSender',
  );
}
